rootProject.name = "AlphaContest"
include(":app")
include(":base")
include(":design")
include(":feature:login")
include(":network")
include(":shared:token")
include(":feature:registration")
include(":feature:add-card")
include(":feature:main-cards")
include(":shared:utils")
include(":feature:profile")
include(":shared:database")
include(":feature:card-detail")
