server:
  port: 8080

logging:
  level:
    root: info

geo-api:
  url: https://catalog.api.2gis.com
  key: changeit

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: changeit
    password: changeit
    url: changeit
