server:
  port: 8080

logging:
  level:
    root: info

geo-api:
  url: https://catalog.api.2gis.com
  key: changeit
  mock-response-path: "./src/main/resources/api/rawMockResponse"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: changeit
    password: changeit
    url: changeit
